### PR TITLE
update pacman options

### PR DESCRIPTION
**Pull request by mio-19**

### CODE REVIEW

**Comment by jlobue10** [comment]
Totally understandable that you (and likely other users) don't want other unrelated packages being updated. I guess I did not notice this (constantly allowing Discover to update on my Steam Deck) and thought it was harmless (similar to `sudo apt-get update && sudo apt-get upgrade on Ubuntu to download any installed package updates). Since the root partitions are so limited in space on the Steam Deck, this is totally reasonable to not want that. :)

Let me review. If I'm happy with all of the changes, I will merge shortly.

**Comment by jlobue10** [comment]
Merged. Thank you for the contribution. :)

**Comment by mio-19** [comment]
Also SteamOS is not designed to upgrading this way.

Discover only touches flatpak packages, not pacman packages

**Comment by jlobue10** [comment]
Good to know. Thanks again.

**Pull request merged**
