### PR TITLE
cleanup bash scripts:

### PR DESCRIPTION
**Pull request by mio-19**
+ never upgrade the whole system (use `-Sy` instead of `-Syu`)
+ use `--noconfirm` option instead of `yes |`
+ remove unnecessary `yes |`
+  `rm -f` instead of `yes | rm`

### CODE REVIEW

**Comment by jlobue10** [comment]
I'll agree to some of these merge requests, but not all. We can have a discussion on which ones I will accept and which ones I will not, if necesary. The yes pipe throughs for both `cp` and `rm` commands will stay in case of system aliases prompting the user even when `-f` is used. The yes pipethroughs are to bypass this. For `pacman` I will gladly change from `-Syu` to `-Sy` and replace the yes pacman pipethroughs with `--noconfirm`. Hopefully this makes sense, and you are okay with my reasoning.

**Review by jlobue10 — CHANGES_REQUESTED** [review]
I will not approve the removal of the `yes` pipethroughs for the `cp` and `rm` commands, as some system `aliases` may still prompt the user even when `-f` is passed. Your requested changes for those are functionally no different than what is already there, really just a change based on  preference. I'd prefer to keep the `yes` pipethroughs for those commands. For the `pacman` changes, I need to confirm on my end that `-Sy` still has the intended functionality that is desired. This should be a simple test when I get home to verify. I am okay with removing the `yes` pipethroughs for the `pacman` commands in favor of `--noconfirm` . Please make those requested changes, so that I can review again.

**Comment by jlobue10** [comment]
Resubmit a new pull request and only include the `sudo pacman -Sy --noconfirm` changes. I will not pull in the others (`cp` and `rm`) since there is nothing functionally wrong with use the `yes |` method and it's more robust in cases where `cp` may be aliased to `cp -i` (similar issue with rm) where users could be prompted even with `-f` argument. Those changes are imperceptible to the end user anyways (save milliseconds... maybe?), and functionally your changes there do not really make a difference (preference).

I will happily merge the `pacman` changes though. Thank you.

Also, if anyone is looking to make a more substantial merge, the one outstanding issue that I would like addressed is someone figuring out the validators to allow typing in the line edit boxes for the background and OS icons (for now they are read-only and can only be updated from browse buttons). I want anything that is not a valid (and existing) PNG file to be rejected. That is the only real change that I'd like at this point. I just don't have any time to look into it myself for the next month or so with work being extremely busy.

**Comment by mio-19** [comment]
> For the `pacman` changes, I need to confirm on my end that `-Sy` still has the intended functionality that is desired. 

I noticed that `-Syu` trying to upgrading unrelated packages when I was running the script. I don't want those packages being updated, so I interrupted and edit the script. This is the original reason why I pr to the project

**Pull request closed without merging**
