### PR TITLE
[Windows SD card, Dual boot fix, 121 issue] Update README.md

### PR DESCRIPTION
**Pull request by Nikoroq**
Updated Windows on SD card instructions and windows' side script dual boot fix instructions provided. Under 29/08/2024 tag (CTRL + F) added two notes about rEFInd GUI SD card [bug](https://github.com/jlobue10/SteamDeck_rEFInd/issues/121).

### CODE REVIEW

**Review by Nikoroq — COMMENTED** [review]
Extended Windows on SD card instructions, Dual boot fix installation instructions and mention of still alive bug which was explained in issue #121

**Comment by jlobue10** [comment]
Merged. Thank you for taking the time to update the README. I will fix the SD card bug at some point.

**Comment by Nikoroq** [comment]
> Merged. Thank you for taking the time to update the README. I will fix the SD card bug at some point.

It's my pleasure to assist. 

As i mentioned: "29/08/2024" is a date of recognition and a tag to find lines (2 in total) which can be removed after bug is fixed.

Thank you for your project. I love it.

**Comment by jlobue10** [comment]
Yes, no problem. I'll try to fix the SD card issue when I can find time and possibly add an option for different icon sizes, if I can test and confirm that works. I need to fix a tooltip typo and maybe add a few other QoL improvements if I can think of any (icon spacing, etc.).

**Pull request merged**
